### ISSUE TITLE
Long time operation problems (Yunlin Branch)

### ISSUE THREAD

**Issue by LynetteLo** [OpenISDM/issue_tracker#8]
Description:
After LBeacon runs continuously for 3 or 4 days, the receiving device will not receive the signal which is sent by Lbeacon, but Raspberry Pi sends the indicator light to flash normally.
The problem Lbeacon is A07, A09, A15, A17, A19 (the rest is not tested).

Device:
 LBeacon A07, A09, A15, A17, A19

Date:
05/16/2018

**Comment by ChengYen-Tang** [comment]
將故障Beacon送回中研院
